
# still working on generalizing makefile to build everything in the directory
# for now:
#
# gcc -Wall -Werror -Wextra -g -o hello hello.c





# CFLAGS=-Wall -Werror -Wextra -g
#
# all: ext16
#
# clean:
# 	rm -f ext16

